# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Merge

on:
  push:
    branches:
      - main
      - dev

jobs:
  ci-lint:
    name: Lint
    uses: ./.github/workflows/ci-lint.yml

  ci-test:
    name: Test
    uses: ./.github/workflows/ci-test.yml
    secrets: inherit

  ci-build:
    name: Build
    needs: [ci-lint, ci-test]
    uses: ./.github/workflows/ci-build.yml

  ci-release:
    name: Release
    needs: ci-build
    uses: ./.github/workflows/ci-release.yml
    secrets: inherit

  ci-finale:
    name: Finale
    needs: ci-release
    uses: ./.github/workflows/ci-finale.yml
