# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: PR

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci-lint:
    name: Lint
    uses: ./.github/workflows/ci-lint.yml

  ci-test:
    name: Test
    uses: ./.github/workflows/ci-test.yml
    secrets: inherit

  ci-build:
    name: Build
    needs: [ci-lint, ci-test]
    uses: ./.github/workflows/ci-build.yml
